### PR TITLE
Add arm64 debian images

### PR DESCRIPTION
**Pull request by cosmo0920**
Nowadays, ARMv8 CPU are sometimes used in embedded Linux boards.

e.g.) Renesas RZ/G2 series use armv8 CPU:
* https://www.cip-project.org/blog/2018/10/23/renesas-rz-g2m-96ce-board-adopted-as-arm64-reference-board-for-the-next-cip-slts-kernel

RZ/G2 and R-Car M3 are used in CIP (Civil Infrastructure Platform) which
is mainly used for Automotive Grade Linux (AGL).

* Jetson TX2 and such recently Jeston series boards use ARMv8 CPU.

Signed-off-by: Hiroshi Hatake <hatake@clear-code.com>

The previous user request is for adding ARM64 image in #128.

### CODE REVIEW

**Comment by cosmo0920** [comment]
@repeatedly @ganmacs How do you think about supporting arm64 platform on Fluentd Docker image?

**Comment by cosmo0920** [comment]
I can build this arm64 image with `make DOCKERFILE=v1.7/arm64/debian VERSION=v1.7.4-debian-arm64-2.0` on macOS Catalina.

**Comment by repeatedly** [comment]
Could you update v1.7 to v1.8?

**Comment by cosmo0920** [comment]
Sure, Will do.

**Comment by cosmo0920** [comment]
I'd updated this PR to v1.8 from v1.7.

**Comment by cosmo0920** [comment]
I've confirmed Jetson TX2 with JetPack 4.3 (latest JetPack) can handle arm64 image and build arm64 image
I also want to add arm64 image support. :muscle:

**Comment by repeatedly** [comment]
Thanks!

**Comment by cosmo0920** [comment]
Whoa, thank you for merging!

**Comment by repeatedly** [comment]
We can't build this image on docker hub: https://hub.docker.com/repository/registry-1.docker.io/fluent/fluentd/builds/bc7ae8e7-65e6-462c-980d-31b414f831d5
Do we need to build and push this image manually?

**Comment by cosmo0920** [comment]
I think that we should do manually.
I can build and push arm64 image same as windows image.

**Comment by cosmo0920** [comment]
And armhf container had not been built since v1.6....
https://hub.docker.com/repository/registry-1.docker.io/fluent/fluentd/builds/bc8a4916-4028-40a5-a5cc-b92519bc84ed

**Comment by repeatedly** [comment]
Yeah. docker hub recently failed to build armhf image...
I'm not sure what is the problem.

**Comment by cosmo0920** [comment]
Oh....

**Comment by cosmo0920** [comment]
I'm investigating why DockerHub autobuild doesn't build armhf and aarch64 images.

**Comment by cosmo0920** [comment]
I've registered a PR (#203) to fix armhf and arm64 images building on DockerHub.

**Pull request merged**
