### PR TITLE
Add Fluentd v1.13.0 images

### PR DESCRIPTION
**Pull request by kenhys**

### CODE REVIEW

**Comment by kenhys** [comment]
Checking docker build

* [x] alpine
* [x] arm64
* [x] armhf
* [x] debian
* [ ] 2004
* [ ] 20H2
* [ ] ltsc2019

**Comment by kenhys** [comment]
It stalls with `*** Removed specs cache ***`...

**Comment by kenhys** [comment]
> It stalls with `*** Removed specs cache ***`...

I doubt that the image may be built but `docker images` doesn't show it. Hmm.
(Windows 10 21H1, Docker Engine v20.10.6, and still dockerd.exe consume 30% continuously)

https://github.com/fluent/fluentd-docker-image/pull/270/files#diff-28b7554bb0449c765034d46df17564c613771856b561847673eeb44d88a25da7R31-R40

There may be something wrong after `gem sources --clear-all`.

```dockerfile
# Remove gem cache and chocolatey
RUN powershell -Command "Remove-Item -Force C:\ruby26\lib\ruby\gems\2.6.0\cache\*.gem; Remove-Item -Recurse -Force 'C:\ProgramData\chocolatey'"

COPY fluent.conf /fluent/conf/fluent.conf


ENV FLUENTD_CONF="fluent.conf"

EXPOSE 24224 5140

ENTRYPOINT ["cmd", "/k", "fluentd", "-c", "C:\\fluent\\conf\\fluent.conf"]
```

**Comment by kenhys** [comment]
hmm, hit the https://github.com/microsoft/hcsshim/issues/696 or https://github.com/docker/for-win/issues/3229?

How about @cosmo0920 ?

**Comment by cosmo0920** [comment]
> hmm, hit the [microsoft/hcsshim#696](https://github.com/microsoft/hcsshim/issues/696) or [docker/for-win#3229](https://github.com/docker/for-win/issues/3229)?
> 
> How about @cosmo0920 ?

It's curious.
As usual, this issue is caused by old MSYS2 and updating huge amount of packages within `ridk exec pacman -Syu --noconfirm` step.
But, MSYS2 `20210419.0.0` is the latest stable released version.... :thinking:

**Comment by cosmo0920** [comment]
And we should update using Dockerfile paths on GitHub Actions:
https://github.com/fluent/fluentd-docker-image/blob/master/.github/workflows/linux.yml#L12-L13

**Comment by cosmo0920** [comment]
> There may be something wrong after `gem sources --clear-all`.

I tested with removed `gem sources --clear-all` step but no luck.

**Comment by cosmo0920** [comment]
I split installing MSYS2 and gems into 2 steps as follows:

```dockerfile
RUN refreshenv \
&& ridk exec pacman -Syu --noconfirm \
&& ridk install 2 3
RUN echo gem: --no-document >> C:\ProgramData\gemrc \
&& gem install cool.io -v 1.5.4 --platform ruby \
&& gem install oj -v 3.3.10 \
&& gem install json -v 2.2.0 \
&& gem install fluentd -v 1.13.0 \
&& gem install win32-service -v 2.1.6 \
&& gem install win32-ipc -v 0.7.0 \
&& gem install win32-event -v 0.6.3 \
&& gem install windows-pr -v 1.2.6 \
&& gem sources --clear-all
```

But it no luck, too. :confounded:

**Comment by kenhys** [comment]
Updated  .github/workflows/linux.yml and it is ok as expected.

**Comment by kenhys** [comment]
I've checked whether rest of file related operations such as  `gem sources --clear-all` , `powershell -Command "Remove-Item ...` and `COPY fluent.conf /fluent/conf/fluent.conf` affects (by comment out them), but it does not change the situation.
(As `Removed specs cache` is shown by gem sources --clear-all, so something wrong in more early stage....)

**Comment by cosmo0920** [comment]
> but it does not change the situation.
> (As `Removed specs cache` is shown by gem sources --clear-all, so something wrong in more early stage....)

Yes. I think so, too.
I'd got similar situations for several times, it suddenly resolved by upgrading MSYS2.
But Currently, our using MSYS2 installer is still the previous latest stable version.
How about using the current very fresh stable version of MSYS2 installer?
https://github.com/msys2/msys2-installer/releases/tag/2021-06-04
https://community.chocolatey.org/packages/msys2/20210604.0.0

If with the current very fresh stable version of MSYS2 makes to be buildable on Windows Server Core images, we should use this fresh stable version of MSYS2.

**Comment by cosmo0920** [comment]
(And we also should push Fluentd v1.12.4 images for Windows Server Core. I'd forgotten to build them. :confounded:)

**Comment by cosmo0920** [comment]
I'm confirming whether upgrading MSYS2 is effective to be able to build Windows images....

**Comment by cosmo0920** [comment]
I'd registered docker building stall issue patch for Windows images: https://github.com/fluent/fluentd-docker-image/pull/271

**Comment by cosmo0920** [comment]
@kenhys Could you rebase off master? I think that https://github.com/fluent/fluentd-docker-image/pull/271 is effective to resolve stucking of Windows docker images building.

**Comment by ashie** [comment]
We should add resolv 0.2.1, or downgrade Ruby to 2.6.6 to avoid https://github.com/fluent/fluentd/issues/3382

**Comment by ashie** [comment]
BTW ruby 2.6 ends the normal maintenance phase: https://www.ruby-lang.org/en/news/2021/04/05/ruby-2-6-7-released/
Should we use ruby 2.7.2? (2.7.3 has also broken resolv).

**Comment by cosmo0920** [comment]
> BTW ruby 2.6 ends the normal maintenance phase: https://www.ruby-lang.org/en/news/2021/04/05/ruby-2-6-7-released/
> Should we use ruby 2.7.2? (2.7.3 has also broken resolv).

Our fluentd-docker-image is used by fluentd-kubernetes-daemonset images.
If we upgrade Ruby version to v2.7, we should confirm that Ruby 2.7 is workable on kubernetes daemonset images...

**Comment by cosmo0920** [comment]
> We should add resolv 0.2.1, or downgrade Ruby to 2.6.6 to avoid [fluent/fluentd#3382](https://github.com/fluent/fluentd/issues/3382)

I guess that adding resolv v0.2.1 is better than rollback Ruby version to 2.6.6....

**Comment by ashie** [comment]
I see. Let's go with ruby 2.6.7 & v0.2.1 for this release.

**Comment by ashie** [comment]
> Our fluentd-docker-image is used by fluentd-kubernetes-daemonset images.

BTW I think v1.12 image should be also updated to fix resolv's issue.
What do you think about it? @cosmo0920

**Comment by cosmo0920** [comment]
> > Our fluentd-docker-image is used by fluentd-kubernetes-daemonset images.
> 
> BTW I think v1.12 image should be also updated to fix resolv's issue.
> What do you think about it? @cosmo0920

Yes, we should do.
But Windows images still use Ruby 2.6.5 because chocolatey does not package Ruby 2.6.6 and 2.6.7:
https://community.chocolatey.org/packages/ruby#versionhistory
We should do that work for Linux images(alpine/debian).

**Comment by ashie** [comment]
Yes, I've checked it.

**Comment by cosmo0920** [comment]
> @kenhys Could you rebase off master? I think that #271 is effective to resolve stucking of Windows docker images building.

#271 is effective for stucking to build Windows images.
I'd confirmed that Windows images can be built with MSYS2 20210604.0.0.

**Comment by cosmo0920** [comment]
> > > Our fluentd-docker-image is used by fluentd-kubernetes-daemonset images.
> > 
> > 
> > BTW I think v1.12 image should be also updated to fix resolv's issue.
> > What do you think about it? @cosmo0920
> 
> Yes, we should do.
> But Windows images still use Ruby 2.6.5 because chocolatey does not package Ruby 2.6.6 and 2.6.7:
> https://community.chocolatey.org/packages/ruby#versionhistory
> We should do that work for Linux images(alpine/debian).

I'd sent in https://github.com/fluent/fluentd-docker-image/pull/272.

**Comment by cosmo0920** [comment]
Could you resolve conflicts?
#272 makes merging conflicts against Makefile....

**Comment by kenhys** [comment]
Ok, I'll do it.

**Comment by kenhys** [comment]
Now, v1.13.0 is ready to build :tada:

**Review by cosmo0920 — APPROVED** [review]

**Comment by kenhys** [comment]
> We need to check whether resolv gem is correctly loaded or not.
It seems that v1.12 image doesn't load it: #272 (comment)

I'll create another PR to fix it.

**Comment by kenhys** [comment]
I've created PR for loading resolv issue for v1.12
https://github.com/fluent/fluentd-docker-image/pull/275

**Comment by kenhys** [comment]
I'll resolve the conflict.

**Comment by cosmo0920** [comment]
Any blocker to merge and publish Fluentd v1.13.0 images?

**Comment by ashie** [comment]
Sorry, just forgot to merge.

**Comment by cosmo0920** [comment]
No problem. Let's publish the new images.
But currently, DockerHub reached 25 rules on its limitation of defined build rules.
Sould we remove v0.12 building definitions from DockerHub?

**Comment by ashie** [comment]
> Sould we remove v0.12 building definitions from DockerHub?
:+1:

**Comment by cosmo0920** [comment]
I removed the definitions for Fluentd v0.12 and kicked Fluentd v1.13 image buildings.

**Comment by cosmo0920** [comment]
@kenhys Could you publish your built Windows Server images?

**Comment by kenhys** [comment]
ok, I'll try.

**Comment by kenhys** [comment]
done!

**Comment by kenhys** [comment]
```
make DOCKERFILE=v1.13/windows-20H2 VERSION=v1.13.0-windows-20H2-1.0
make DOCKERFILE=v1.13/windows-20H2 VERSION=v1.13-windows-20H2-1

make DOCKERFILE=v1.13/windows-2004 VERSION=v1.13.0-windows-2004-1.0
make DOCKERFILE=v1.13/windows-2004 VERSION=v1.13-windows-2004-1

make DOCKERFILE=v1.13/windows-ltsc2019 VERSION=v1.13.0-windows-ltsc2019-1.0
make DOCKERFILE=v1.13/windows-ltsc2019 VERSION=v1.13-windows-ltsc2019-1



docker push fluent/fluentd:v1.13.0-windows-20H2-1.0
docker push fluent/fluentd:v1.13-windows-20H2-1
docker push fluent/fluentd:v1.13.0-windows-2004-1.0
docker push fluent/fluentd:v1.13-windows-2004-1
docker push fluent/fluentd:v1.13.0-windows-ltsc2019-1.0
docker push fluent/fluentd:v1.13-windows-ltsc2019-1
```

**Pull request merged**
