### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by gimmi**
Uopdated sample `Dockerfile` to create new alpine dockerd image with additional plugins

### CODE REVIEW

**Comment by repeatedly** [comment]
Does this patch cleanup `RUN` command, right?

**Comment by gimmi** [comment]
Yes, `sudo` does not work on alpine

**Comment by ganmacs** [comment]
I checked the original Dockerfile which contains `sudo`. it worked.
could you tell me if there are any additionals command?

```
$ cat Dockerfile
FROM fluent/fluentd:v1.6-1
# Use root account to use apk
USER root
# below RUN includes plugin as examples elasticsearch is not required
# you may customize including plugins as you wish
RUN apk add --no-cache --update --virtual .build-deps \
        sudo build-base ruby-dev \
 && sudo gem install fluent-plugin-elasticsearch \
 && sudo gem sources --clear-all \
 && apk del .build-deps \
 && rm -rf /tmp/* /var/tmp/* /usr/lib/ruby/gems/*/cache/*.gem

COPY fluent.conf /fluentd/etc/

COPY entrypoint.sh /bin/

USER fluent
$ docker build -t fluent-custom:v1.6 .
Sending build context to Docker daemon   5.12kB
Step 1/6 : FROM fluent/fluentd:v1.6-1
v1.6-1: Pulling from fluent/fluentd
e7c96db7181b: Already exists
2dc13b9c3b9a: Pull complete
9f1188d2a912: Pull complete
0655e59af7f9: Pull complete
94bf634efed8: Pull complete
Digest: sha256:17e3e8a268fda02a417addc542bbe60f81834aeb15d12e85d68425def3063892
Status: Downloaded newer image for fluent/fluentd:v1.6-1
 ---> ff6f3b926c47
Step 2/6 : USER root
 ---> Running in 302c373142b2
Removing intermediate container 302c373142b2
 ---> 3dfe0a2f97e0
Step 3/6 : RUN apk add --no-cache --update --virtual .build-deps         sudo build-base ruby-dev  && sudo gem install fluent-plugin-elasticsearch  && sudo gem sources --clear-all  && apk del .build-deps  && rm -rf /tmp/* /var/tmp/* /usr/lib/ruby/gems/*/cache/*.gem
 ---> Running in 86ee92b4b106
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
(1/23) Installing sudo (1.8.25_p1-r2)
(2/23) Installing binutils (2.31.1-r2)
(3/23) Installing libmagic (5.36-r0)
(4/23) Installing file (5.36-r0)
(5/23) Installing isl (0.18-r0)
(6/23) Installing libgomp (8.3.0-r0)
(7/23) Installing libatomic (8.3.0-r0)
(8/23) Installing libgcc (8.3.0-r0)
(9/23) Installing mpfr3 (3.1.5-r1)
(10/23) Installing mpc1 (1.0.3-r1)
(11/23) Installing libstdc++ (8.3.0-r0)
(12/23) Installing gcc (8.3.0-r0)
(13/23) Installing musl-dev (1.1.20-r4)
(14/23) Installing libc-dev (0.7.1-r0)
(15/23) Installing g++ (8.3.0-r0)
(16/23) Installing make (4.2.1-r2)
(17/23) Installing fortify-headers (1.0-r0)
(18/23) Installing build-base (0.5-r1)
(19/23) Installing libgmpxx (6.1.2-r1)
(20/23) Installing gmp-dev (6.1.2-r1)
(21/23) Installing pkgconf (1.6.0-r0)
(22/23) Installing ruby-dev (2.5.5-r0)
(23/23) Installing .build-deps (0)
Executing busybox-1.29.3-r10.trigger
OK: 189 MiB in 50 packages
Successfully installed excon-0.65.0
Successfully installed multi_json-1.13.1
Successfully installed multipart-post-2.1.1
Successfully installed faraday-0.15.4
Successfully installed elasticsearch-transport-7.2.0
Successfully installed elasticsearch-api-7.2.0
Successfully installed elasticsearch-7.2.0
Successfully installed fluent-plugin-elasticsearch-3.5.2
8 gems installed
*** Removed specs cache ***
(1/23) Purging .build-deps (0)
(2/23) Purging sudo (1.8.25_p1-r2)
(3/23) Purging build-base (0.5-r1)
(4/23) Purging file (5.36-r0)
(5/23) Purging g++ (8.3.0-r0)
(6/23) Purging gcc (8.3.0-r0)
(7/23) Purging binutils (2.31.1-r2)
(8/23) Purging libatomic (8.3.0-r0)
(9/23) Purging libgomp (8.3.0-r0)
(10/23) Purging make (4.2.1-r2)
(11/23) Purging libc-dev (0.7.1-r0)
(12/23) Purging musl-dev (1.1.20-r4)
(13/23) Purging fortify-headers (1.0-r0)
(14/23) Purging ruby-dev (2.5.5-r0)
(15/23) Purging gmp-dev (6.1.2-r1)
(16/23) Purging libgmpxx (6.1.2-r1)
(17/23) Purging libmagic (5.36-r0)
(18/23) Purging isl (0.18-r0)
(19/23) Purging libstdc++ (8.3.0-r0)
(20/23) Purging libgcc (8.3.0-r0)
(21/23) Purging mpc1 (1.0.3-r1)
(22/23) Purging mpfr3 (3.1.5-r1)
(23/23) Purging pkgconf (1.6.0-r0)
Executing busybox-1.29.3-r10.trigger
OK: 28 MiB in 27 packages
Removing intermediate container 86ee92b4b106
 ---> 6bd14d824d9e
Step 4/6 : COPY fluent.conf /fluentd/etc/
 ---> 350683d3f228
Step 5/6 : COPY entrypoint.sh /bin/
 ---> 0784029e9d34
Step 6/6 : USER fluent
 ---> Running in 459b95b87ca2
Removing intermediate container 459b95b87ca2
 ---> 7c2f2b494320
Successfully built 7c2f2b494320
Successfully tagged fluent-custom:v1.6
```

**Comment by gimmi** [comment]
Interesting, I was sure that `sudo` command was not available in alpine (without using [some workaround](https://stackoverflow.com/a/55277849) at least).

Anyway, I think that all the `sudo` prefix in the commands can be safely removed because are useless.

**Pull request closed without merging**
