### PR TITLE
Add post_checkout hooks for automatic builds of ARM images

### PR DESCRIPTION
**Pull request by elezar**
This PR adds a `post_checkout` hook for building ARM images on Docker Hub.

This is a follow-up on #124 

I have triggered the build in my own Docker Hub account here: https://hub.docker.com/r/elezar/fluentd-docker-image/builds/bw9e7spgn8bsdcd3iekcda6/

### CODE REVIEW

**Comment by elezar** [comment]
> Thanks. Could you recommit with -s?

Sure. Just noticed that too.

**Comment by repeatedly** [comment]
Ah, I see. Thanks.

**Comment by repeatedly** [comment]
Merged. Waiting for building new image...

**Comment by elezar** [comment]
Just noticed that I didn't run `make src-all` to generate all the files for the `debian-onbuild` images 🤦‍♂️

**Pull request merged**
