### PR TITLE
Update alpine to 3.6

### PR DESCRIPTION
**Pull request by Globegitter**

### CODE REVIEW

**Comment by Globegitter** [comment]
Not sure why the Debian 0.12 test is failing but all the others are passing.

**Comment by repeatedly** [comment]
Alpine Linux seems to use ruby 2.4.
No need dockerfile update?

**Comment by arush-sal** [comment]
@repeatedly With the critical vulnerability present in current images, is there any specific reason why this hasn't been merged yet? Let me know if I can help out with anything.

**Comment by repeatedly** [comment]
@arush-sal Alpine is now 3.7 so if there is no problem, we want to go 3.7.
I have already commented about PATH. Do we need to change ruby related path in doc? > https://github.com/fluent/fluentd-docker-image#alpine-version

**Comment by repeatedly** [comment]
Closed. https://github.com/fluent/fluentd-docker-image/pull/112 uses newer version.

**Pull request closed without merging**
