### PR TITLE
Fix docs/scripts inconsistent issue

### PR DESCRIPTION
**Pull request by guessi**
* Fix Markdown links reference error
* Fix inconsistent sample code in README.md
* Fix missing description for Windows-series
* Fix missing description for v0.14-series
* Refine README.md for the section of "Supported Tags"

### CODE REVIEW

**Comment by repeatedly** [comment]
No need to add v1.3 to Makefile because v1.3 images are never updated.
Sorry for the confusion. By historical reason, `stable` refers v1.3 images for compatibility.

**Comment by guessi** [comment]
@repeatedly got it, will update later

**Comment by guessi** [comment]
@repeatedly removed `v1.3` from `Makefile`

here comes another question, should I change the line
`v1.4/alpine:v1.4.2-1.0,v1.4-1,edge`
to
`v1.4/alpine:v1.4.2-1.0,v1.4-1,stable,latest` ?

**Comment by ganmacs** [comment]
Sorry for the late reply. Could you resolve conflicts?

> here comes another question, should I change the line
v1.4/alpine:v1.4.2-1.0,v1.4-1,edge
to
v1.4/alpine:v1.4.2-1.0,v1.4-1,stable,latest ?

I don't think so. latest is v1.3 since the README says  https://github.com/fluent/fluentd-docker-image/tree/dabca3c327d08be6d43a8919316a57ca2228e603#stable-latest (cc @repeatedly)

**Comment by repeatedly** [comment]
Yes. Currently, `latest` and `stable` are for old images.

**Comment by guessi** [comment]
@repeatedly looks like you have updated these changes on master branch.

**Comment by guessi** [comment]
@repeatedly I've rebased and updated for the fixes, please review while you are free, thanks.

**Comment by repeatedly** [comment]
Thanks!

**Pull request merged**
