### PR TITLE
Bump version to v1.15.3-1.2 to update Ruby to v3.1.3

### PR DESCRIPTION
**Pull request by ashie**
Signed-off-by: Takuro Ashie <ashie@clear-code.com>

### CODE REVIEW

**Review by kenhys — COMMENTED** [review]
v1.15/windows-ltsc2019/Dockerfile
v1.15/windows-ltsc2022/Dockerfile

It still points to 3.1.2.1, but it seems that  3.1.3.1 is available.
https://community.chocolatey.org/packages/ruby#versionhistory

Any blockers?

**Comment by ashie** [comment]
I just forgot to update it.

**Comment by ashie** [comment]
I've updated them.

**Review by kenhys — APPROVED** [review]
LGTM

**Comment by ashie** [comment]
I've rebuilt GNU/Linux images.

**Pull request merged**
