### PR TITLE
Add Fluentd v1.13.2 images

### PR DESCRIPTION
**Pull request by kenhys**

### CODE REVIEW

**Comment by kenhys** [comment]
checking local builds.

**Comment by kenhys** [comment]
It seems ok.

**Review by cosmo0920 — APPROVED** [review]
Looks nice!

**Comment by kenhys** [comment]
kicked trigger.

**Comment by kenhys** [comment]
done.


make DOCKERFILE=v1.13/windows-20H2 VERSION=v1.13.2-windows-20H2-1.0
make DOCKERFILE=v1.13/windows-20H2 VERSION=v1.13-windows-20H2-1
make DOCKERFILE=v1.13/windows-2004 VERSION=v1.13.2-windows-2004-1.0
make DOCKERFILE=v1.13/windows-2004 VERSION=v1.13-windows-2004-1
make DOCKERFILE=v1.13/windows-ltsc2019 VERSION=v1.13.2-windows-ltsc2019-1.0
make DOCKERFILE=v1.13/windows-ltsc2019 VERSION=v1.13-windows-ltsc2019-1

docker push fluent/fluentd:v1.13.2-windows-20H2-1.0
docker push fluent/fluentd:v1.13-windows-20H2-1
docker push fluent/fluentd:v1.13.2-windows-2004-1.0
docker push fluent/fluentd:v1.13-windows-2004-1
docker push fluent/fluentd:v1.13.2-windows-ltsc2019-1.0
docker push fluent/fluentd:v1.13-windows-ltsc2019-1

**Pull request merged**
