### PR TITLE
Switch Ruby base image to Debian buster

### LINKED ISSUE #199: Upgrade debian's base image to buster
https://hub.docker.com/_/ruby repository now has buster images, so we can switch to buster.

### PR DESCRIPTION
**Pull request by fgreinacher**
Resolves #199

### CODE REVIEW

**Comment by fgreinacher** [comment]
The Debian images I changed are looking alright, any idea why Travis jobs for unchanged images are failing?

**Comment by repeatedly** [comment]
Thanks for the patch!

In travis, tests are sometimes failed by unexpected error, failed to image download, failed install packages, etc. Maybe their environment issue.

**Comment by fgreinacher** [comment]
Thanks for merging. Will this be pushed to Docker Hub automatically?

**Comment by repeatedly** [comment]
No. I just updated the image on docker hub.
After finished kubecon, I will apply changes to k8s daemonset.

**Pull request merged**
