### PR TITLE
update to alpine 3.8 and bump dumb-init

### PR DESCRIPTION
**Pull request by ajayk**
- upgrade to alpine 3.8
- bump dump-init to 1.2.1

### CODE REVIEW

**Comment by repeatedly** [comment]
Alpine 3.8's ruby version is same as 3.7?

**Comment by ajayk** [comment]
alpine 3.8  
`ruby 2.5.2p104 (2018-10-18 revision 65133) [x86_64-linux-musl]
`

alpine 3.7
`ruby 2.4.5p335 (2018-10-18 revision 65137) [x86_64-linux-musl]
`

**Comment by PeterDaveHello** [comment]
As the Ruby version was changed, the tests also need to be updated.

**Comment by repeatedly** [comment]
No need update because no reason to use v1.1.
And we want to focus on debian for newer platform like armhf.

**Comment by repeatedly** [comment]
And yes, need to update test for ruby version: https://github.com/fluent/fluentd-docker-image/blob/master/test/suite.bats
@ajayk Could you update the patch?

**Comment by repeatedly** [comment]
I noticed alpine's ruby removes important modules and it breaks fluentd.
Need to install `ruby-etc` and `ruby-webrick` together with apk.

**Comment by repeatedly** [comment]
Thanks!

**Pull request merged**
