### PR TITLE
fix: try to import gpg key from multiple servers

### PR DESCRIPTION
**Pull request by robsonpeixoto**
- [ ] https://github.com/dlpco/bank-auth-keycloak
 - [ ] https://github.com/dlpco/banking-aml-api
 - [ ] https://github.com/dlpco/banking-inside-gateway
 - [ ] https://github.com/dlpco/banking-ledger
 - [ ] https://github.com/dlpco/banking-order-management-system
 - [ ] https://github.com/dlpco/banking-panda
 - [ ] https://github.com/dlpco/banking-payment-dispatcher
 - [ ] https://github.com/dlpco/banking-pyser
 - [ ] https://github.com/dlpco/banking-pyser-file-manager
 - [ ] https://github.com/dlpco/banking-str-settlement
 - [ ] https://github.com/dlpco/banking-transfers
 - [ ] https://github.com/dlpco/event-processor-integration
 - [ ] https://github.com/dlpco/ex-bank
 - [ ] https://github.com/dlpco/str-integration-engine
 - [ ] https://github.com/dlpco/tasks-api

### CODE REVIEW

**Comment by lag-linaro** [comment]
Couple of things here.

Firstly, if you make this change to one `Dockerfile` you should apply the change to all 33 of them.

Secondly, this is not the right approach.  Please see https://github.com/docker-library/official-images/issues/4252#issuecomment-381783035 for details.

**Comment by robsonpeixoto** [comment]
Thanks @lag-linaro.
I updated all images. Please, review again

**Comment by robsonpeixoto** [comment]
I'm without time to do it now. If would you like to close this issue as son as possible, feel free to close it.
But I can do it this weekend.

**Comment by lag-linaro** [comment]
What is it that you can do this weekend?

**Pull request closed without merging**
