### PR TITLE
Reorganize project

### PR DESCRIPTION
**Pull request by tyranron**
This pull request reorganizes project structure from branch-oriented to directory-oriented.

There are a couple of _cons_ with branch-oriented project structure:
- For users it's hard to understand what versions are actual at the moment. Also, it's harder to search required Dockerfile/configureation.
- It makes maintainers to repeat changes and maintain stuff in different branches separately, so complicates maintaining.

Directory-oriented approach to maintain multi-version Docker image repository:
- Ability to use "normal" Git flow: `master` branch contains all latest stable versions and Docker Hub runs builds on it. Any other branches can be used for development and do not represent an interest for end users.
- All the stuff located in one place, so simple to maintain and investigate.
- Allows simple automation of almost all project operations.

TODO
- [x] Change project layout
- [x] Add EditorConfig rules
- [x] Implement Makefile
- [x] Merge versioned branches and add their images
- [x] Dockerfile generation from template
- [x] Docker Hub `post_push` hook generation
- [x] Bats tests & Travis CI integration
- [x] Update README
- [x] Write `MAINTAINING.md`

### CODE REVIEW

**Comment by tyranron** [comment]
@repeatedly would you be so kind to enable Travis CI for this repo?

**Comment by repeatedly** [comment]
Done: https://travis-ci.org/fluent/fluentd-docker-image

**Comment by tyranron** [comment]
@repeatedly it's done and may be merged.

BEFORE merge to `master`:
1. Change [build triggers on Docker Hub]( https://hub.docker.com/r/fluent/fluentd/~/settings/automated-builds). They should look like:

     Type | Name  | Dockerfile Location  | Docker Tag Name
    ---|---|---|---
    Branch | master | /v0.12/alpine/ | v0.12
    Branch | master | /v0.12/alpine-onbuild/ | v0.12-onbuild
    Branch | master | /v0.14/alpine/ | v0.14
    Branch | master | /v0.14/alpine-onbuild/ | v0.14-onbuild

    Nothing less, nothing more.

2. [On the same page](https://hub.docker.com/r/fluent/fluentd/~/settings/automated-builds) specify `alpine` in "Repository Links" section.  
This is required to trigger automatic rebuild if parent image is updated.


AFTER merge to `master`:
- Git branches `onbuild`, `v0.12`, `v0.12-onbuild`, `v0.14`, `v0.14-onbuild` may be removed as not necessary anymore.
- [Docker tags](https://hub.docker.com/r/fluent/fluentd/tags/) `v0.12-latest`, `v0.12-latest-onbuild`, `v0.14-latest`, `v0.14-latest-onbuild` may be removed to avoid confusing people in future.

**Comment by tyranron** [comment]
After merge I'll be able to add Debian-based image versions.

**Comment by repeatedly** [comment]
Just merged. Thanks for the great contribution!

**Pull request merged**
