### PR TITLE
Debian images

### PR DESCRIPTION
**Pull request by tyranron**
This PR adds Debian-based images to project.  
These images may be used when some plugin cannot be installed in Alpine due to unresolvable system library dependencies (like [fluent-plugin-systemd problem](https://github.com/fluent/fluentd-docker-image/issues/49)).

- Used `debian:stretch-slim` parent image to keep smaller image size.
- Refactored Dockerfile a bit (added distro packages and ca-certificates upgrading).
- Removed deprecated Ubuntu-based image.

#### BEFORE merge to `master`
1. Add the following [build triggers on Docker Hub]( https://hub.docker.com/r/fluent/fluentd/~/settings/automated-builds):

     Type | Name  | Dockerfile Location  | Docker Tag Name
    ---|---|---|---
    Branch | master | /v0.12/debian/ | v0.12-debian
    Branch | master | /v0.12/debian-onbuild/ | v0.12-debian-onbuild
    Branch | master | /v0.14/debian/ | v0.14-debian
    Branch | master | /v0.14/debian-onbuild/ | v0.14-debian-onbuild

    As the result, there should be exactly 8 build triggers totally.

2. [On the same page](https://hub.docker.com/r/fluent/fluentd/~/settings/automated-builds) specify `debian` in "Repository Links" section.  
This is required to trigger automatic rebuild if parent image is updated.  
As the result, there should be 2 repositories totally (`alpine` and `debian`).

### CODE REVIEW

**Comment by gianrubio** [comment]
@tyranron it's hard to read the Dockerfile template, why not split the Dockerfile for ubuntu/alpine?

**Comment by tyranron** [comment]
Squashed and rebased on latest `master`.

@repeatedly would you be so kind to review?

**Comment by ryanwalls** [comment]
Would be great to also update the main readme.md with an example of how to use the debian `on-build` image to add your own plugins.  (Since there is already an example there for the alpine version.)

**Comment by tyranron** [comment]
@ryanwalls ok, will do.

**Comment by ryanwalls** [comment]
@tyranron Also, trying out this Dockerfile, it appears that Debian installing Ruby 2.1.5 instead of 2.3.0.  So you will probably need to update your gem paths.

**Comment by tyranron** [comment]
@ryanwalls maybe just update base image from `jessie` to `stretch`?

**Comment by repeatedly** [comment]
Separating Dockerfile for each OS is not good approach?

**Comment by tyranron** [comment]
@repeatedly not sure that understood well what exactly you are asking here.

Separate Dockerfiles for each OS is good approach when multiple environments are required. We're exactly in that case.

**Comment by repeatedly** [comment]
In this patch, each build shares Dockerfile.template.erb.
How about separating this file into `Dockerfile.alpine.template.erb` and `Dockerfile.ubuntu.template.erb`?

**Comment by tyranron** [comment]
@repeatedly oh, understood.

Actually, no problems, if you'd like.

On my opinion it's better to keep that stuff in one template because:
- Those Dockerfiles are not different much. So, with high probability possible changes to them are required for both versions, and editing 2 files is worse than editing one file.
- In one template it's easier to see the exact difference between OS version, and compare them without extra diffs.

**Comment by tyranron** [comment]
@ryanwalls `README.md` is updated with Debian example. Is it enough?

**Comment by ryanwalls** [comment]
@tyranron Yep, that's great!

**Comment by tyranron** [comment]
@ryanwalls what about moving to `stretch` instead `jessie`? What is your opinion on it?

**Comment by tyranron** [comment]
@repeatedly please do not merge it yet. There is still one question (with ruby version) to be resolved. After it's done I'll rebase and squash on latest `master` and notify you that it can be merged.

**Comment by repeatedly** [comment]
@tyranron okay.

**Comment by ryanwalls** [comment]
@tyranron I'm good with moving to `stretch`.

**Comment by tyranron** [comment]
@repeatedly done. Can be merged.

**Comment by repeatedly** [comment]
Building debian images is done: https://hub.docker.com/r/fluent/fluentd/tags/

**Pull request merged**
