### PR TITLE
Add Fluentd v1.13.3 images

### PR DESCRIPTION
**Pull request by kenhys**

### CODE REVIEW

**Comment by kenhys** [comment]
https://community.chocolatey.org/packages/msys2/20210725.0.0 is not approved yet, so postpone updating to newer msys2.

**Comment by kenhys** [comment]
v1.13.3-windows-ltsc2019-1.0 will fail?

**Comment by kenhys** [comment]
> v1.13.3-windows-ltsc2019-1.0 will fail?

This was my local environment issue.

**Review by cosmo0920 — APPROVED** [review]
Looks good. :+1:

**Comment by kenhys** [comment]
rebased.

**Comment by kenhys** [comment]
trigger on

**Comment by cosmo0920** [comment]
:tada:

**Pull request merged**
